import { Recept } from "./recept";

export const recipes: Recept[] = [
  new Recept(
    "1",
    "Spaghetti Bolognese",
    "https://cdn.aniagotuje.com/pictures/articles/2024/05/61816591-v-1080x1080.jpg",
    [
      "spaghetti",
      "ground beef",
      "onion",
      "garlic",
      "tomato paste",
      "canned tomatoes",
      "olive oil",
      "salt",
      "pepper",
      "basil",
    ],
    [
      "Boil spaghetti according to package instructions.",
      "In a pan, sauté onion and garlic in olive oil until soft.",
      "Add ground beef and cook until browned.",
      "Stir in tomato paste and canned tomatoes, simmer 10–15 min.",
      "Season with salt, pepper, basil.",
      "Serve sauce over spaghetti.",
    ]
  ),
  new Recept(
    "2",
    "Chicken Alfredo Pasta",
    "https://familystylefood.com/wp-content/uploads/2023/04/Chicken-Fettuccine-Pasta.jpg",
    [
      "fettuccine",
      "chicken breast",
      "butter",
      "heavy cream",
      "parmesan cheese",
      "garlic",
      "salt",
      "pepper",
    ],
    [
      "Cook fettuccine according to package directions.",
      "Season and cook chicken breast; slice it.",
      "In same pan, melt butter and sauté garlic.",
      "Add heavy cream, bring to simmer, stir in parmesan.",
      "Add chicken and pasta to sauce, toss to coat.",
      "Serve hot.",
    ]
  ),
  new Recept(
    "3",
    "Vegetable Stir-Fry with Rice",
    "https://cookingwithcoit.com/wp-content/uploads/2021/04/HERO_Vegetable-Stir-Fry.jpg",
    [
      "rice",
      "broccoli",
      "bell pepper",
      "carrot",
      "soy sauce",
      "garlic",
      "ginger",
      "sesame oil",
    ],
    [
      "Cook rice as per instructions.",
      "Heat sesame oil in wok, sauté garlic and ginger.",
      "Add veggies and stir-fry until crisp-tender.",
      "Add soy sauce and mix.",
      "Serve veggies over rice.",
    ]
  ),
  new Recept(
    "4",
    "Beef Tacos",
    "https://tarateaspoon.com/wp-content/uploads/2024/04/Beef-Taco-Meat-sz-03.jpg",
    [
      "taco shells",
      "ground beef",
      "onion",
      "taco seasoning",
      "lettuce",
      "tomato",
      "cheddar cheese",
      "sour cream",
    ],
    [
      "Cook ground beef with chopped onion until browned.",
      "Stir in taco seasoning with some water; simmer.",
      "Fill taco shells with beef, lettuce, tomato, cheese, sour cream.",
      "Serve immediately.",
    ]
  ),
  new Recept(
    "5",
    "Thai Green Curry",
    "https://rachelcooksthai.com/wp-content/uploads/2011/05/Green-Curry-Eggplant-01.jpg",
    [
      "chicken or tofu",
      "green curry paste",
      "coconut milk",
      "eggplant",
      "bell pepper",
      "bamboo shoots",
      "fish sauce",
      "basil",
      "rice",
    ],
    [
      "Cook rice separately.",
      "In pan, heat a little oil, fry green curry paste until fragrant.",
      "Add coconut milk and stir to combine.",
      "Add chicken or tofu and vegetables; simmer until cooked.",
      "Season with fish sauce, stir in basil.",
      "Serve over rice.",
    ]
  ),
  new Recept(
    "6",
    "Pancakes",
    "https://plus.unsplash.com/premium_photo-1663854478296-dd00b6257021?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFuY2FrZXN8ZW58MHx8MHx8fDA%3D",
    ["flour", "milk", "egg", "baking powder", "sugar", "salt", "butter"],
    [
      "Mix flour, baking powder, sugar, salt in bowl.",
      "Whisk milk and egg, then combine with dry ingredients.",
      "Heat pan, melt a bit of butter.",
      "Pour batter to make pancakes; cook until bubbles form then flip.",
      "Serve with syrup or fruit.",
    ]
  ),
  new Recept(
    "7",
    "Tomato Soup",
    "https://www.inspiredtaste.net/wp-content/uploads/2016/08/Tomato-Soup-Recipe-1-1200.jpg",
    [
      "tomatoes",
      "onion",
      "garlic",
      "vegetable broth",
      "olive oil",
      "cream (optional)",
      "salt",
      "pepper",
    ],
    [
      "Sauté onion and garlic in olive oil.",
      "Add tomatoes and broth, bring to simmer.",
      "Blend until smooth.",
      "Return to heat, stir in cream if using, season.",
      "Serve warm.",
    ]
  ),
  new Recept(
    "8",
    "Caesar Salad",
    "https://plus.unsplash.com/premium_photo-1664478283448-94d7b72a23ed?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2Flc2FyJTIwc2FsYWR8ZW58MHx8MHx8fDA%3D",
    [
      "romaine lettuce",
      "croutons",
      "parmesan cheese",
      "anchovy fillets (optional)",
      "garlic",
      "olive oil",
      "lemon juice",
      "egg yolk or mayo",
      "salt",
      "pepper",
    ],
    [
      "Make dressing: mash garlic and anchovy, whisk with egg yolk (or mayo), olive oil, lemon juice, salt, pepper.",
      "Toss lettuce, croutons, and dressing.",
      "Top with parmesan shavings and serve.",
    ]
  ),
  new Recept(
    "9",
    "Chocolate Chip Cookies",
    "https://hips.hearstapps.com/hmg-prod/images/250512-pwm-cowgirl-4x3-68c04b8bd5bb7.jpg?crop=1xw:1xh;center,top&resize=1200:*",
    [
      "flour",
      "baking soda",
      "salt",
      "butter",
      "sugar",
      "brown sugar",
      "egg",
      "vanilla extract",
      "chocolate chips",
    ],
    [
      "Preheat oven to 175 °C.",
      "Cream butter and sugars, then beat in egg and vanilla.",
      "Mix in dry ingredients, then fold in chocolate chips.",
      "Drop spoonfuls onto baking sheet.",
      "Bake ~10–12 min until edges golden.",
      "Cool and serve.",
    ]
  ),
  new Recept(
    "10",
    "Omelette",
    "https://www.demotivateur.fr/images-buzz/105978/omelette-parfaite-classique.jpg",
    [
      "eggs",
      "milk",
      "salt",
      "pepper",
      "butter",
      "fillings (cheese, ham, vegetables)",
    ],
    [
      "Beat eggs with milk, salt, pepper.",
      "Melt butter in a pan over medium heat.",
      "Pour egg mixture, let it set slightly.",
      "Add fillings on one half, fold omelette.",
      "Cook until done, slide onto plate.",
    ]
  ),
  new Recept(
    "11",
    "Chili con Carne",
    "https://previews.123rf.com/images/margouillat/margouillat1801/margouillat180100869/94501281-chili-con-carne.jpg",
    [
      "ground beef",
      "onion",
      "garlic",
      "kidney beans",
      "canned tomatoes",
      "tomato paste",
      "chili powder",
      "cumin",
      "salt",
      "pepper",
    ],
    [
      "Sauté onion and garlic, add ground beef and cook until browned.",
      "Add tomato paste, canned tomatoes, beans.",
      "Season with chili, cumin, salt, pepper; simmer 20–30 min.",
      "Serve with rice or bread.",
    ]
  ),
  new Recept(
    "12",
    "Grilled Cheese Sandwich",
    "https://www.recipetineats.com/tachyon/2023/07/Grilled-Cheese-sandwich-photo-main.jpg?resize=900%2C1125&zoom=1",
    ["bread", "butter", "cheese slices"],
    [
      "Butter one side of each bread slice.",
      "Place cheese between unbuttered sides.",
      "Grill in pan until golden on both sides and cheese melted.",
      "Serve immediately.",
    ]
  ),
  new Recept(
    "13",
    "Shrimp Fried Rice",
    "https://www.dinneratthezoo.com/wp-content/uploads/2019/05/shrimp-fried-rice-5.jpg",
    [
      "rice (cooked, cold)",
      "shrimp",
      "egg",
      "peas & carrots (mixed)",
      "soy sauce",
      "sesame oil",
      "green onion",
      "garlic",
    ],
    [
      "Scramble egg and set aside.",
      "In wok, heat sesame oil, sauté garlic.",
      "Add shrimp and cook until pink.",
      "Add peas & carrots, stir-fry a bit.",
      "Add rice and soy sauce, mix well.",
      "Stir in scrambled egg and green onion, serve.",
    ]
  ),
  new Recept(
    "14",
    "Pancetta & Pea Risotto",
    "https://foodandjourneys.net/wp-content/uploads/2021/12/Pea-and-Pancetta-Risotto-PIC1.jpg",
    [
      "arborio rice",
      "pancetta (or bacon)",
      "onion",
      "garlic",
      "white wine",
      "chicken broth",
      "frozen peas",
      "parmesan cheese",
      "butter",
      "salt",
      "pepper",
    ],
    [
      "Cook pancetta until crisp; remove and set aside.",
      "Sauté onion and garlic in same pot.",
      "Add rice, stir to coat.",
      "Pour wine, stir until absorbed.",
      "Add broth gradually, stirring, until rice nearly done.",
      "Stir in peas, butter, parmesan, pancetta; season and serve.",
    ]
  ),
  new Recept(
    "15",
    "Margherita Pizza",
    "https://www.abeautifulplate.com/wp-content/uploads/2015/08/the-best-homemade-margherita-pizza-1-4.jpg",
    [
      "pizza dough",
      "tomato sauce",
      "mozzarella cheese",
      "fresh basil",
      "olive oil",
      "salt",
    ],
    [
      "Preheat oven to highest temp and prepare pizza stone or tray.",
      "Stretch dough, spread tomato sauce.",
      "Add mozzarella, drizzle olive oil, sprinkle salt.",
      "Bake until crust crisp and cheese bubbly.",
      "Top with fresh basil and serve.",
    ]
  ),
  new Recept(
    "16",
    "Lentil Soup",
    "https://www.healthyseasonalrecipes.com/wp-content/uploads/2021/08/lentil-soup-029.jpg",
    [
      "lentils",
      "carrot",
      "celery",
      "onion",
      "garlic",
      "vegetable broth",
      "olive oil",
      "salt",
      "pepper",
    ],
    [
      "Sauté onion, garlic, carrot, celery in olive oil until soft.",
      "Add lentils and broth; bring to boil.",
      "Simmer until lentils tender (~20–30 min).",
      "Season with salt and pepper.",
      "Blend partly if desired, serve hot.",
    ]
  ),
  new Recept(
    "17",
    "Eggplant Parmesan",
    "https://www.allrecipes.com/thmb/5uZ3e3ifoj-nzr6lQtSCvQkPUFs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5068161-eef00c8c5553490d894800642e1dd9ec.jpg",
    [
      "eggplant",
      "flour",
      "egg",
      "breadcrumbs",
      "tomato sauce",
      "mozzarella cheese",
      "parmesan cheese",
      "olive oil",
      "salt",
      "pepper",
    ],
    [
      "Slice eggplant, salt and let sit to remove moisture.",
      "Dredge in flour, egg, breadcrumbs; fry or bake slices.",
      "In baking dish, layer sauce, eggplant, cheeses.",
      "Bake until cheese melted and golden.",
      "Serve warm.",
    ]
  ),
  new Recept(
    "18",
    "Banana Bread",
    "https://img.kidspot.com.au/q6HCTf9r/w643-h428-cfill-q90/kk/2016/05/easy-banana-bread-612173-1.jpg",
    [
      "ripe bananas",
      "flour",
      "sugar",
      "butter",
      "egg",
      "baking soda",
      "salt",
      "vanilla extract",
    ],
    [
      "Preheat oven to 175 °C.",
      "Mash bananas, mix with melted butter.",
      "Stir in sugar, egg, vanilla.",
      "Mix in flour, baking soda, salt.",
      "Pour into loaf pan and bake ~60 min or until done.",
      "Cool and slice.",
    ]
  ),
  new Recept(
    "19",
    "Chicken Paprikash",
    "https://carolinagelen.com/wp-content/uploads/2023/01/9f5d5552-16bc-4672-ad77-7e3a0859f7ba_1370x1028.jpgg",
    [
      "chicken pieces",
      "onion",
      "garlic",
      "paprika",
      "tomato paste",
      "chicken broth",
      "sour cream",
      "flour",
      "salt",
      "pepper",
    ],
    [
      "Sauté onion and garlic until soft.",
      "Brown chicken pieces in the pan.",
      "Stir in paprika and tomato paste.",
      "Add broth, bring to simmer, cover and cook until chicken done.",
      "Mix sour cream with flour, stir into sauce to thicken.",
      "Season and serve (often with noodles or potatoes).",
    ]
  ),
  new Recept(
    "20",
    "Vegetarian Chili",
    "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_728,h_546/k%2Farchive%2F9fff417ed363c61374bb3a2523683b9949b51fb9",
    [
      "kidney beans",
      "black beans",
      "onion",
      "garlic",
      "bell pepper",
      "canned tomatoes",
      "corn",
      "chili powder",
      "cumin",
      "salt",
      "pepper",
    ],
    [
      "Sauté onion, garlic, bell pepper until soft.",
      "Add beans, tomatoes, corn.",
      "Season with chili powder, cumin, salt, pepper.",
      "Simmer 20–30 min for flavors to meld.",
      "Serve with rice or bread.",
    ]
  ),
];
